server:
  port: 5000

spring:
  application:
    name: service-zuul
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    hi-api:
      path: /hipai/**
      serviceId: eureka-demo-client
    feignapi:
      path: /ribbonapi/**
      serviceId: eureka-feign-client
