server:
  port: 5000
logging:
  file: "logs/boot-admin-sample.log"

spring:
  application:
    name: spring-cloud-admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

boot:
  admin:
    routes:
      endpoints: env,metrics , dump , jolokia , info , configprops , trace , logfile , refresh ,flyway , liquibase, heapdump ,l oggers , auditevents , hystrix . stream
    turbine:
      clusters: default
      location: service- turbine