server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    #关闭自我保护机制, 否则服务关闭时, 还是显示为UP
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 3