server:
  port: 9411

spring:
  application:
    name: zipkin-server

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10